language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
script: phpunit --bootstrap spitfire/bootstrap.php --coverage-clover=coverage.clover bin/tests

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover  | mail -s Clover output cesar@magic3w.com
