language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
script: if [ "$TRAVIS_PHP_VERSION" == "5.5" ]; then phpunit --bootstrap spitfire/bootstrap.php --coverage-clover=coverage.clover bin/tests; else phpunit --bootstrap spitfire/bootstrap.php --coverage-clover=coverage.clover --whitelist="spitfire|bin" bin/tests; fi;

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - if [ -f coverage.clover ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
