language: php
php:
  - 7.3
script: phpunit --configuration=bin/tests/phpunit.xml bin/tests

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - if [ -f /tmp/coverage.xml ]; then php ocular.phar code-coverage:upload --format=php-clover /tmp/coverage.xml; fi;
