language: php
php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm
script: phpunit --bootstrap spitfire/bootstrap.php bin/tests --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover