#!/usr/bin/php
<?php

/**
 * This is the main file of Spitfire, it is in charge of loading
 * system settings (for custom operation) and also of summoning
 * spitfire and loading the adequate controller for every single
 * request. It also makes sure that error logging is sent to
 * terminal / log file instead of to the user.
 * 
 * @package Spitfire
 * @author César de la Cal <cesar@magic3w.com>
 * @copyright 2018 Magic3W - All rights reserved
 */

/* Include Spitfire core.
 */
define('BASEDIR', __DIR__);

include __DIR__ . '/vendor/autoload.php';
include __DIR__ . '/bin/bootstrap.php';

/* Call the selected controller with the selected method. */
exit(spitfire()->fire());