<?php namespace spitfire\validation;

/**
 * Validates that the length of a content is bigger than the indicated minimum
 * length. This validates only data as strings which may cause unexpected 
 * behavior if you try to test the length of an array.
 * 
 * @author César de la Cal <cesar@magic3w.com>
 */
class MinLengthValidationRule implements ValidationRule
{
	/**
	 * The minimum length a string passed to this element must have for the test
	 * to be passed successfully.
	 * @var int
	 */
	private $length;
	
	/**
	 * A message the validation error generated by this object should carry to give
	 * the end user information about the reason his input was rejected.
	 * @var string
	 */
	private $message;
	
	/**
	 * Additional information given to the user in case the validation did not 
	 * succeed. This message can hold additional infos on how to solve the error.
	 * @var string
	 */
	private $extendedMessage;
	
	public function __construct($length, $message, $extendedMessage = '') {
		$this->length = $length;
		$this->message = $message;
		$this->extendedMessage = $extendedMessage;
	}
	
	/**
	 * Tests a value with this validation rule. Returns the errors detected for
	 * this element or boolean false on no errors.
	 * 
	 * @param mixed $value
	 * @param mixed $source
	 * @return \spitfire\validation\ValidationError|boolean
	 */
	public function test($value) {
		if (strlen($value) < $this->length) {
			return new ValidationError($this->message, $this->extendedMessage);
		}
		return false;
	}

}